name: Player Infos Workflow
on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username of the player'
        required: true
      level:
        description: 'Level of the player'
        required: true
      class:
        description: 'Class of the player'
        required: true
        default: 'jedi'
        options: ['jedi', 'sith', 'rebel']

jobs:
  player_infos:
    runs-on: ubuntu-latest
    steps:
    - name: Display Player Infos
      run: echo "Le joueur ${{ github.event.inputs.username }} est de niveau ${{ github.event.inputs.level }} et joue un ${{ github.event.inputs.class }}."
